title: Shashi Singh
description: "My personal website"
url: "https://singhshashi.github.io"

google_analytics: UA-68377788-1
show_downloads: true
remote_theme: zerostatic/jekyll-atlantic-theme

gems:
  - jekyll-mentions
