baseURL = "https://singhshashi.github.io/"
languageCode = "en-us"
title = "Shashi S Singh"
theme = "mini"

[pagination]
  pagerSize = 10

# Permalinks
[permalinks]
  posts = "/blog/:slug/"
  projects = "/projects/:slug/"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Main navigation menu
[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

# Site parameters
[params]
  author = "Shashi S Singh"
  authorFull = "Shashi Shekhar Singh"
  description = "Developer and Tech Entrepreneur"
  tagline = "Building products that matter"

  [params.social]
    github = "singhshashi"
    linkedin = "singhshashishekhar"
    twitter = "_singhshashi"
    email = ""

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
